version: '3.8'

services:
  postgresql:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=asistencia  
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./postgres/usuario.sql:/docker-entrypoint-initdb.d/data.sql

  soabus:
    image: jrgiadach/soabus:v1
    ports:
      - '5000:5000' 